{"post-title": "How data science and rocket science will get humans to\u00a0Mars", "href": "https://techcrunch.com/2016/11/19/how-data-science-and-rocket-science-will-get-humans-to-mars/"}
{"post-title": "Big data can\u2019t bring objectivity to a subjective\u00a0world", "href": "https://techcrunch.com/2016/11/18/big-data-cant-bring-objectivity-to-a-subjective-world/"}
{"post-title": "Microsoft offers concessions to EU regulators eyeing its $26.2B LinkedIn\u00a0bid", "href": "https://techcrunch.com/2016/11/16/microsoft-offers-concessions-to-eu-regulators-eyeing-its-26-2bn-linkedin-bid/"}
{"post-title": "Elastic brings order to its product line with Elastic\u00a0Stack", "href": "https://techcrunch.com/2016/10/26/elastic-finally-brings-order-to-its-product-line-with-elastic-stack/"}
{"post-title": "Alluxio launches its memory-centric storage system for big data\u00a0workloads", "href": "https://techcrunch.com/2016/10/26/alluxio-launches-its-memory-centric-storage-system-for-big-data-workloads/"}
{"post-title": "Dataiku grabs $14 million for its collaborative data science\u00a0platform", "href": "https://techcrunch.com/2016/10/25/dataiku-grabs-14-million-for-its-collaborative-data-science-platform/"}
{"post-title": "Singapore\u2019s Nugit raises $5.2M to make sense of big data using artificial\u00a0intelligence", "href": "https://techcrunch.com/2016/10/07/nugit/"}
{"post-title": "Why Salesforce might be interested in\u00a0Twitter", "href": "https://techcrunch.com/2016/09/24/why-salesforce-might-be-interested-in-twitter/"}
{"post-title": "Student projects leapfrog governments and industry in \u2018Data Science for Social Good\u2019\u00a0program", "href": "https://techcrunch.com/2016/08/26/student-projects-leapfrog-governments-and-industry-in-data-science-for-social-good-program/"}
{"post-title": "Responding to the demand for reliable data collection in Africa, mSurvey raises seed\u00a0funding", "href": "https://techcrunch.com/2016/08/26/responding-to-the-demand-for-reliable-data-collection-in-africa-msurvey-raises-seed-funding/"}
{"post-title": "Is big data in big\u00a0trouble?", "href": "https://techcrunch.com/2016/08/19/is-big-data-in-big-trouble/"}
{"post-title": "NextHealth raises $8.5M from Norwest to drive down medical\u00a0costs", "href": "https://techcrunch.com/2016/08/18/nexthealth-raises-8-5m-from-norwest-to-drive-down-medical-costs/"}
{"post-title": "Big data\u2019s humble\u00a0beginnings", "href": "https://techcrunch.com/2016/08/14/big-datas-humble-beginnings/"}
{"post-title": "BloomReach wants to deliver meaningful data directly to online\u00a0merchandizers", "href": "https://techcrunch.com/2016/08/09/bloomreachs-latest-brings-the-data-directly-to-online-merchandizers/"}
{"post-title": "Latest Amazon Elastic MapReduce release supports 16 Hadoop\u00a0projects", "href": "https://techcrunch.com/2016/08/02/latest-aws-elastic-mapreduce-release-supports-16-hadoop-projects/"}
{"post-title": "NSF dedicates $35 million to improving software used in science and\u00a0education", "href": "https://techcrunch.com/2016/08/01/nsf-dedicates-35-million-to-improving-software-used-in-science-and-education/"}
{"post-title": "Big data integrator Talend pops 54% in Nasdaq debut, raising\u00a0$94.5M", "href": "https://techcrunch.com/2016/07/29/big-data-integrator-talend-pops-56-in-nasdaq-debut-raising-94-5m/"}
{"post-title": "Too much big data running through my\u00a0brain", "href": "https://techcrunch.com/2016/07/17/too-much-big-data-running-through-my-brain/"}
{"post-title": "Big data and its developer\u00a0fallout", "href": "https://techcrunch.com/2016/07/16/big-data-and-its-developer-fallout/"}
{"post-title": "To succeed in IoT, hire a chief data\u00a0officer", "href": "https://techcrunch.com/2016/07/11/to-succeed-in-iot-hire-a-chief-data-officer/"}
{"post-title": "Beamery raises $2 million to help recruiters identify and draw in talent, instead of waiting for\u00a0applicants", "href": "https://techcrunch.com/2016/06/16/beamery-raises-2-million-to-help-recruiters-identify-and-draw-in-talent-instead-of-waiting-for-applicants/"}
{"post-title": "$30M Stampede 2 supercomputer will provide 18 petaflops of data-crunching power to researchers\u00a0nationwide", "href": "https://techcrunch.com/2016/06/06/30m-stampede-2-supercomputer-will-provide-18-petaflops-of-data-crunching-power-to-researchers-nationwide/"}
{"post-title": "Microsoft bets on Apache Spark to power its big data and analytics\u00a0services", "href": "https://techcrunch.com/2016/06/06/microsoft-bets-on-apache-spark-to-power-its-big-data-and-analytics-services/"}
{"post-title": "FirstMark Capital\u2019s Matt Turck on the big data\u00a0landscape", "href": "https://techcrunch.com/2016/05/30/firstmark-capitals-matt-turck-on-the-big-data-landscape/"}
{"post-title": "Preparing for infrastructures of the\u00a0future", "href": "https://techcrunch.com/2016/05/25/learnings-from-google-about-the-future-of-infrastructure/"}
{"post-title": "Cray\u2019s latest supercomputer runs OpenStack and open source big data\u00a0tools", "href": "https://techcrunch.com/2016/05/24/crays-latest-supercomputer-runs-openstack-and-open-source-big-data-tools/"}
{"post-title": "How storage is changing in the age of big\u00a0data", "href": "https://techcrunch.com/2016/05/22/how-storage-is-changing-in-the-age-of-big-data/"}
{"post-title": "Investors serve up $50 million for ThoughtSpot\u2019s search engine for enterprise\u00a0data", "href": "https://techcrunch.com/2016/05/19/investors-serve-up-50-million-for-thoughtspots-search-engine-for-enterprise-data/"}
{"post-title": "Shift Technology grabs $10 million to prevent fraudulent insurance\u00a0claims", "href": "https://techcrunch.com/2016/05/18/shift-technology-grabs-10-million-to-prevent-fraudulent-insurance-claims/"}
{"post-title": "The digital age of data\u00a0art", "href": "https://techcrunch.com/2016/05/08/the-digital-age-of-data-art/"}
{"post-title": "eBay acquires AI-powered big data processor\u00a0Expertmaker", "href": "https://techcrunch.com/2016/05/05/ebay-acquires-ai-powered-big-data-processor-expertmaker/"}
{"post-title": "Strengthening authentication through big\u00a0data", "href": "https://techcrunch.com/2016/05/01/strengthening-authentication-through-big-data/"}
{"post-title": "Seven things to watch for at Strata + Hadoop World 2016 in San\u00a0Jose", "href": "https://techcrunch.com/2016/03/29/seven-things-to-watch-for-at-strata-hadoop-world-2016-in-san-jose/"}
{"post-title": "Newcomer Galactic Exchange can spin up a Hadoop cluster in five\u00a0minutes", "href": "https://techcrunch.com/2016/03/24/newcomer-galactic-exchange-can-spin-up-a-hadoop-cluster-in-five-minutes/"}
{"post-title": "Altiscale\u2019s latest cloud service brings Hadoop to business\u00a0users", "href": "https://techcrunch.com/2016/03/15/altiscales-latest-cloud-product-brings-big-data-to-business-users/"}
{"post-title": "Alooma scores $11.2 million Series A to solve data science pain\u00a0points", "href": "https://techcrunch.com/2016/03/14/alooma-scores-11-2-million-series-a-to-solve-data-science-pain-points/"}
{"post-title": "Big data and the Death\u00a0Star", "href": "https://techcrunch.com/2016/03/13/big-data-and-the-death-star/"}
{"post-title": "Tableau scores advanced database tech with acquisition of German startup\u00a0HyPer", "href": "https://techcrunch.com/2016/03/10/tableau-scores-advanced-database-tech-with-acquisition-of-german-startup-hyper/"}
{"post-title": "The singularity is never coming, but it\u2019s already\u00a0here", "href": "https://techcrunch.com/2016/03/03/the-singularity-is-never-coming-but-its-already-here/"}
{"post-title": "LinkedIn open-sources its WhereHows data discovery and lineage\u00a0portal", "href": "https://techcrunch.com/2016/03/03/linkedin-open-sources-its-wherehows-data-discovery-and-lineage-portal/"}
{"post-title": "Getting predictive about politics (and everything\u00a0else)", "href": "https://techcrunch.com/2016/03/01/getting-predictive-about-politics-and-everything-else/"}
{"post-title": "Innovations In Cybersecurity At RSA\u00a02016", "href": "https://techcrunch.com/2016/02/29/innovations-in-cybersecurity-at-rsa-2016/"}
{"post-title": "Don\u2019t Dread Data Ethics And\u00a0Governance", "href": "https://techcrunch.com/2016/02/23/dont-dread-data-ethics-and-governance/"}
{"post-title": "Optimizing Analytics On Time Series\u00a0Databases", "href": "https://techcrunch.com/2016/02/19/optimizing-analytics-on-time-series-databases-a-supply-chain-perspective/"}
{"post-title": "IBM Acquiring Truven Health Analytics For $2.6 Billion And Adding It To Watson\u00a0Health", "href": "https://techcrunch.com/2016/02/18/ibm-acquiring-truven-health-analytics-for-2-6-billion-and-adding-it-to-watson-health/"}
{"post-title": "Databricks Launches Free Community Edition As Companion To Free Online Spark\u00a0Courses", "href": "https://techcrunch.com/2016/02/17/databricks-releases-free-community-edition-as-spark-teaching-tool/"}
{"post-title": "IBM Launches Quarks Open Source Development Tool To Build Efficient IoT\u00a0Apps", "href": "https://techcrunch.com/2016/02/15/ibm-launches-quarks-open-source-development-tool-to-build-apps-from-iot-sensor-data/"}
{"post-title": "As Primary Season Opens, OpenText Releases Election News Tracking\u00a0Tool", "href": "https://techcrunch.com/2016/02/01/as-primary-season-opens-opentext-releases-election-news-tracking-tool/"}
{"post-title": "IBM Closes Weather Co. Purchase, Names David Kenny New Head Of Watson\u00a0Platform", "href": "https://techcrunch.com/2016/01/29/ibm-watson-weather-company-sale/"}
{"post-title": "StatMuse Picks Up $10M For Its AI-Based, Graphic Search Engine For Sports\u00a0Statistics", "href": "https://techcrunch.com/2016/01/27/statmuse-picks-up-10m-for-its-ai-based-graphic-search-engine-for-sports-statistics/"}
{"post-title": "European Antitrust Chief Eyeing Tech Giants\u2019 Hold On\u00a0Data", "href": "https://techcrunch.com/2016/01/18/european-antitrust-chief-eyeing-tech-giants-hold-on-data/"}
{"post-title": "The 2015 Analytics Software\u00a0Market", "href": "https://techcrunch.com/2016/01/09/the-year-in-analytics/"}
{"post-title": "How To Stem The Global Shortage Of Data\u00a0Scientists", "href": "https://techcrunch.com/2015/12/31/how-to-stem-the-global-shortage-of-data-scientists/"}
{"post-title": "If You\u2019re Launching A Tech Startup In 2016, Focus On Privacy And Fast\u00a0Data", "href": "https://techcrunch.com/2015/12/23/if-youre-launching-a-tech-startup-in-2016-focus-on-privacy-and-fast-data/"}
{"post-title": "SnapLogic Raises $37.5 Million To Help Legacy Data Play Nicely In The\u00a0Cloud", "href": "https://techcrunch.com/2015/12/10/snaplogic-raises-37-5-million-to-help-legacy-data-play-nicely-in-the-cloud/"}
{"post-title": "Platfora Big Data Analytics Platform Scores $30 Million\u00a0Round", "href": "https://techcrunch.com/2015/12/08/platfora-scores-30-million-for-big-data-discovery-platform-growth/"}
{"post-title": "\u201cUnsexy Plumbing,\u201d Integrated Data And The Future Of The Healthcare\u00a0System", "href": "https://techcrunch.com/2015/12/06/unsexy-plumbing-integrated-data-and-the-future-of-the-healthcare-system/"}
{"post-title": "Leveraging Technology To Make Credit\u00a0Credible", "href": "https://techcrunch.com/2015/11/06/three-ways-tech-can-disrupt-the-small-dollar-credit-industry/"}
{"post-title": "Tableau Software Soars 17% On 3Q\u00a0Earnings", "href": "https://techcrunch.com/2015/11/05/tableau-software-soars-17-on-3q-earnings/"}
{"post-title": "How RFID Delivers Big Data On Cows And Milk\u00a0Production", "href": "https://techcrunch.com/2015/11/03/how-rfid-delivers-big-data-on-cows-and-milk-production/"}
{"post-title": "IBM Will Acquire The Weather Company\u2019s Digital\u00a0Business", "href": "https://techcrunch.com/2015/10/28/ibm-will-acquire-the-weather-companys-digital-business/"}
{"post-title": "Michael Jordan, Mark Cuban, Ted Leonsis Betting $44 Million on Sportradar\u2019s\u00a0Data", "href": "https://techcrunch.com/2015/10/27/michael-jordan-mark-cuban-betting-44-million-on-sportradars-data/"}
{"post-title": "Nick Halstead, Founder Of Big Data Analytics Firm DataSift, Steps Down As\u00a0CEO", "href": "https://techcrunch.com/2015/10/23/nick-halstead-founder-of-big-data-analytics-firm-datasift-steps-down-as-ceo/"}
{"post-title": "The California Drought And Standards Of\u00a0IoT", "href": "https://techcrunch.com/2015/10/17/the-california-drought-and-standards-of-iot/"}
{"post-title": "Dell Needs To Decide What To Keep And What To Sell After EMC\u00a0Deal", "href": "https://techcrunch.com/2015/10/14/dell-needs-to-decide-what-to-keep-and-what-to-sell-after-emc-deal/"}
{"post-title": "What\u2019s The Value Of Your\u00a0Data?", "href": "https://techcrunch.com/2015/10/13/whats-the-value-of-your-data/"}
{"post-title": "The Other Ag Sector Problem That Big Data Can\u00a0Solve", "href": "https://techcrunch.com/2015/10/11/the-other-ag-sector-problem-that-big-data-can-solve/"}
{"post-title": "How The Digital Health Revolution Will Become A\u00a0Reality", "href": "https://techcrunch.com/2015/10/07/how-the-digital-health-revolution-will-become-a-reality/"}
{"post-title": "AWS Introduces Kinesis Firehose To Move Sensor Data To\u00a0Cloud", "href": "https://techcrunch.com/2015/10/07/aws-introduces-kinesis-firehose-to-move-sensor-data-to-cloud/"}
{"post-title": "Data Is A Mine And A\u00a0Minefield", "href": "https://techcrunch.com/2015/10/03/data-is-a-mine-and-a-minefield/"}
{"post-title": "Data Driven Everything Remains\u00a0Elusive", "href": "https://techcrunch.com/2015/09/25/data-driven-everything-remains-elusive/"}
{"post-title": "Bursting The Top Three Myths To Get Your Healthcare Startup\u00a0Funded", "href": "https://techcrunch.com/2015/09/19/bursting-the-top-three-myths-to-get-your-healthcare-startup-funded/"}
{"post-title": "The Best Things Come In\u00a0Threes", "href": "https://techcrunch.com/2015/09/15/the-best-things-come-in-threes/"}
{"post-title": "Datos IO Raises $12.5M Series A Round For Its Big Data Recovery\u00a0Platform", "href": "https://techcrunch.com/2015/09/15/datos-io-raises-12-50m-series-a-round-for-its-big-data-recovery-platfrom/"}
{"post-title": "Salesforce Announces New Internet of Things Cloud, As Dreamforce\u00a0Opens", "href": "https://techcrunch.com/2015/09/15/salesforce-announces-new-internet-of-things-cloud-as-dreamforce-opens/"}
{"post-title": "Tech\u2019s Role In Fighting\u00a0Wildfires", "href": "https://techcrunch.com/2015/09/13/techs-role-in-fighting-wildfires/"}
{"post-title": "Building Smart City\u00a0Security", "href": "https://techcrunch.com/2015/09/12/building-smart-city-security/"}
{"post-title": "Big Data Doesn\u2019t\u00a0Exist", "href": "https://techcrunch.com/2015/09/10/big-data-doesnt-exist/"}
{"post-title": "Google Updates Play Games Player Analytics With Improved iOS Support, New Ways To Track\u00a0Players", "href": "https://techcrunch.com/2015/09/09/google-updates-play-games-player-analytics-with-improved-ios-support-new-ways-to-track-players-in-game/"}
{"post-title": "Is Enterprise Hyper Growth The New\u00a0Normal?", "href": "https://techcrunch.com/2015/09/08/is-enterprise-hyper-growth-the-new-normal/"}
{"post-title": "Hortonworks Acquires Onyara, Early Startup With Roots In\u00a0NSA", "href": "https://techcrunch.com/2015/08/25/hortonworks-acquires-onyara-early-startup-with-roots-in-nsa/"}
{"post-title": "Big Data Vendor BlueData Announces $20M Round And Intel\u00a0Partnership", "href": "https://techcrunch.com/2015/08/25/big-data-vendor-bluedata-announces-20m-round-and-intel-collaboration/"}
{"post-title": "Retail Analytics Startup IntelligenceNODE Raises $4M From NEA And\u00a0Orios", "href": "https://techcrunch.com/2015/08/19/intelligencenode/"}
{"post-title": "Datameer Bags $40M Round Led By Singapore Investment\u00a0Firm", "href": "https://techcrunch.com/2015/08/18/datameer-bags-40m-round-led-by-singapore-investment-firm/"}
{"post-title": "The Boom, Not Doom, Of Market\u00a0Failure", "href": "https://techcrunch.com/2015/08/12/the-boom-not-doom-of-market-failure/"}
{"post-title": "IBM Buying Merge Healthcare For $1B To Bring Medical Image Analysis To Watson\u00a0Health", "href": "https://techcrunch.com/2015/08/06/ibm-buying-merge-healthcare-for-1b-to-bring-medical-image-analysis-to-watson-health/"}
{"post-title": "GE Adds Infrastructure Services To Internet Of Things\u00a0Platform", "href": "https://techcrunch.com/2015/08/04/ge-adds-infrastructure-services-to-internet-of-things-platform/"}
{"post-title": "How Businesses Are Leveraging Public Data To Reach Target\u00a0Audiences", "href": "https://techcrunch.com/2015/08/01/how-businesses-are-leveraging-public-data-to-reach-target-audiences/"}
{"post-title": "Data Privacy Just Makes Good Business\u00a0Sense", "href": "https://techcrunch.com/2015/07/17/data-privacy-just-makes-good-business-sense/"}
{"post-title": "Data Virtualization Company Delphix Lands\u00a0$75M", "href": "https://techcrunch.com/2015/07/13/delphix/"}
{"post-title": "Microsoft Hopes To Unify Big Data And Analytics In Newly Announced\u00a0Suite", "href": "https://techcrunch.com/2015/07/13/microsoft-unifies-big-data-and-analytics-in-newly-launched-suite/"}
{"post-title": "Spark And Hadoop Are Friends, Not\u00a0Foes", "href": "https://techcrunch.com/2015/07/12/spark-and-hadoop-are-friends-not-foes/"}
{"post-title": "Don\u2019t Hire A Chief Data Officer Unless You\u2019re Serious About Becoming A Data-Driven\u00a0Company", "href": "https://techcrunch.com/2015/07/07/dont-hire-a-chief-data-officer-unless-youre-serious-about-becoming-a-data-driven-company/"}
{"post-title": "Enterprises Don\u2019t Have Big Data, They Just Have Bad\u00a0Data", "href": "https://techcrunch.com/2015/07/01/enterprises-dont-have-big-data-they-just-have-bad-data/"}
{"post-title": "The Latest Big Data Innovation Is Consumer\u00a0Empowerment", "href": "https://techcrunch.com/2015/06/29/the-latest-big-data-innovation-is-consumer-empowerment/"}
{"post-title": "Komprise Raises $6M To Help Companies Rein In Sprawling\u00a0Data", "href": "https://techcrunch.com/2015/06/18/komprise/"}
{"post-title": "Ex-Googlers Raise $6M For Connectifier, An AI Approach To Recruitment\u00a0Search", "href": "https://techcrunch.com/2015/06/16/ex-googlers-raise-6m-for-connectifier-an-ai-approach-to-recruitment-search/"}
{"post-title": "This Year\u2019s Boston Red Sox Could Be An Argument Against Data-Driven Decision\u00a0Making", "href": "https://techcrunch.com/2015/06/15/this-years-boston-red-sox-could-be-an-argument-against-data-driven-decision-making/"}
{"post-title": "IBM Pours Researchers And Resources Into Apache Spark\u00a0Project", "href": "https://techcrunch.com/2015/06/15/ibm-pours-researchers-and-resources-into-apache-spark-project/"}
{"post-title": "YC Grad Yhat Scores $1.5M In Second Seed\u00a0Round", "href": "https://techcrunch.com/2015/05/30/yc-grad-yhat-scores-1-5m-in-second-seed-round/"}
{"post-title": "Salesforce Helps Customers Ride Wave To Big Data\u00a0Platforms", "href": "https://techcrunch.com/2015/05/28/salesforce-wants-to-ride-wave-to-big-data-platforms/"}
{"post-title": "Rocana Lands $15M To Bring Big Data Analysis To IT\u00a0Ops", "href": "https://techcrunch.com/2015/05/01/rocana-lands-15m-to-bring-big-data-analysis-to-it-ops/"}
{"post-title": "Microsoft Announces Azure Data Lake, A Data Repository For Big Data\u00a0Analytics", "href": "https://techcrunch.com/2015/04/29/microsoft-announces-azure-data-lake-a-data-repository-for-big-data-analytics/"}
{"post-title": "Amazon\u2019s AWS Quietly Acquired NoSQL Database Migration Startup Amiato In May\u00a02014", "href": "https://techcrunch.com/2015/04/20/amazons-aws-acquired-amiato/"}
{"post-title": "Google Opens Cloud Dataflow To All Developers, Launches European Zone For\u00a0BigQuery", "href": "https://techcrunch.com/2015/04/16/google-opens-cloud-dataflow-to-all-developers-launches-european-zone-for-bigquery/"}
{"post-title": "Pepperdata Scores $15M For Hadoop Cluster\u00a0Management", "href": "https://techcrunch.com/2015/04/16/pepperdata-scores-15m-for-hadoop-cluster-performance-management/"}
{"post-title": "Twitter Cuts Off DataSift To Step Up Its Own Big Data\u00a0Business", "href": "https://techcrunch.com/2015/04/11/twitter-cuts-off-datasift-to-step-up-its-own-b2b-big-data-analytics-business/"}
{"post-title": "Cheaper Sensors Will Fuel The Age Of Smart\u00a0Everything", "href": "https://techcrunch.com/2015/03/10/cheaper-sensors-will-fuel-the-age-of-smart-everything/"}
{"post-title": "IBM Watson Group Buys AlchemyAPI To Enhance Machine Learning\u00a0Capabilities", "href": "https://techcrunch.com/2015/03/04/ibm-watson-group-buys-alchemyapi-to-give-it-machine-learning-capabilities/"}
{"post-title": "New Firm Combines Wearables And Data To Improve Decision\u00a0Making", "href": "https://techcrunch.com/2015/02/24/new-firm-combines-wearables-and-data-to-improve-decision-making/"}
{"post-title": "Pivotal Open Sources Key Parts of Its Big Data\u00a0Suite", "href": "https://techcrunch.com/2015/02/17/pivotal-pivots-key-big-data-suite-components-to-open-source/"}
{"post-title": "Datameer Heads To The Cloud With Latest Big Data\u00a0Product", "href": "https://techcrunch.com/2015/02/11/datameer-heads-to-the-cloud-with-latest-big-data-product/"}
{"post-title": "Bottlenose Scores $13.4M To Help Enterprises Spot Emerging Trends And Threats In\u00a0Real-Time", "href": "https://techcrunch.com/2015/02/09/bottlenose-series-b/"}
{"post-title": "YC-Backed Yhat Gives Data Science Teams A Head\u00a0Start", "href": "https://techcrunch.com/2015/02/07/yc-backed-yhat-gives-data-science-teams-a-head-start/"}
{"post-title": "White House Report Sees Potential, Pitfalls Of Big\u00a0Data", "href": "https://techcrunch.com/2015/02/05/white-house-report-sees-potential-pitfalls-of-big-data/"}
{"post-title": "Hockey And Big\u00a0Data", "href": "https://techcrunch.com/2015/01/31/hockey-and-big-data/"}
{"post-title": "Smarking Drives Big Data To Parking\u00a0Industry", "href": "https://techcrunch.com/2015/01/31/smarking-drives-big-data-to-parking-industry/"}
{"post-title": "Facebook\u2019s European Privacy Class Action Hearing Set For April\u00a09", "href": "https://techcrunch.com/2015/01/26/facebooks-european-privacy-class-action-hearing-set-for-april-9/"}
{"post-title": "Rubikloud Raises $7 Million In Funding To Help Retailers Analyze Big\u00a0Data", "href": "https://techcrunch.com/2015/01/19/rubikloud-7m/"}
{"post-title": "French Startup Dataiku Grabs $3.6M To Continue Developing Big Data\u00a0Software", "href": "https://techcrunch.com/2015/01/19/french-startup-dataiku-grabs-3-6m-to-keep-developing-big-data-software/"}
{"post-title": "Finding The Elusive Big Wisdom In Big\u00a0Data", "href": "https://techcrunch.com/2014/12/28/finding-the-elusive-big-wisdom-in-big-data/"}
{"post-title": "RapidMiner Adds Streams To Bring Real Time To Its Big Data\u00a0Processing", "href": "https://techcrunch.com/2014/12/17/rapidminer-adds-streams-to-bring-real-time-to-big-data-processing/"}
{"post-title": "Aiming To Be A \u2018B2B Google\u2019 For Business Intel, Mattermark Raises $6.5M Led By Foundry\u00a0Group", "href": "https://techcrunch.com/2014/12/16/aiming-to-be-a-b2b-google-for-business-intel-mattermark-raises-6-5m-led-by-foundry-group/"}
{"post-title": "Lies, Damn Lies And The Myth Of Following The\u00a0Data", "href": "https://techcrunch.com/2014/12/06/lies-damn-lies-and-the-myth-of-following-the-data/"}
{"post-title": "Mo\u2019 Data Mo\u2019\u00a0Problems", "href": "https://techcrunch.com/2014/11/29/mo-data-mo-problems/"}
{"post-title": "DataFox Brings Private Company Analysis And One-Pagers To\u00a0Mobile", "href": "https://techcrunch.com/2014/11/21/datafox-brings-private-company-analysis-and-one-pagers-to-mobile/"}
{"post-title": "Healthcare\u2019s Big Data\u00a0Opportunity", "href": "https://techcrunch.com/2014/11/20/healthcares-big-data-opportunity/"}
{"post-title": "Searching For Truths In Big, Enormous, Massive\u00a0Data", "href": "https://techcrunch.com/2014/11/19/searching-for-truths-in-big-enormous-massive-data/"}
{"post-title": "Tidemark\u2019s Latest Release Uses Big Data To Help Finance Look Forward Instead Of\u00a0Back", "href": "https://techcrunch.com/2014/11/12/tidemarks-latest-release-uses-big-data-to-help-finance-look-forward-instead-of-back/"}
{"post-title": "Clustree Automagically Matches Internal Talent With Job\u00a0Positions", "href": "https://techcrunch.com/2014/11/11/clustree-automagically-matches-internal-talent-with-job-positions/"}
{"post-title": "Using Big Data To Fight\u00a0Pandemics", "href": "https://techcrunch.com/2014/11/08/using-big-data-to-fight-pandemics/"}
{"post-title": "Twitter Partners With IBM To Bring Social Data To The\u00a0Enterprise", "href": "https://techcrunch.com/2014/10/29/twitter-partners-with-ibm-to-bring-social-data-to-the-enterprise/"}
{"post-title": "Galvanize Announces GalvanizeU, A Year-Long Bootcamp That Gives You A Master\u2019s\u00a0Degree", "href": "https://techcrunch.com/2014/10/23/galvanize-announces-galvanizeu-a-year-long-bootcamp-that-gives-you-a-masters-degree/"}
{"post-title": "Pitching A Means To Automate Data Processing, Xplenty Raises $3\u00a0Million", "href": "https://techcrunch.com/2014/10/20/pitching-a-means-to-automate-data-processing-xplenty-raises-3-million/"}
{"post-title": "Former Netezza Team Reunites And Lands $8M To Solve Today\u2019s Big Data\u00a0Problem", "href": "https://techcrunch.com/2014/10/20/former-netezza-team-gets-8m-to-reunite-to-solve-todays-big-data-problem/"}
{"post-title": "Big Data Analytics Go Large: GoodData Gets $25.7M Led By Intel, Eyes Up 2016\u00a0IPO", "href": "https://techcrunch.com/2014/10/02/big-data-analytics-goes-large-gooddata-raises-25-7m-led-by-intel-eyes-up-2016-ipo/"}
{"post-title": "IBM\u2019s New Watson Analytics Wants To Bring Big Data To The\u00a0Masses", "href": "https://techcrunch.com/2014/09/16/ibms-new-watson-analytics-wants-to-bring-data-to-the-masses/"}
{"post-title": "Three Marks Of Real Data\u00a0Science", "href": "https://techcrunch.com/2014/09/06/three-marks-of-real-data-science/"}
{"post-title": "When Big Data Is Watching\u00a0You", "href": "https://techcrunch.com/2014/08/11/ceed/"}
{"post-title": "Adatao Emerges With $13M In Funding And Visions Of Changing Big\u00a0Data", "href": "https://techcrunch.com/2014/08/07/adatao-emerges-with-13m-in-funding-and-visions-of-changing-big-data/"}
{"post-title": "The Dark Age Of Enterprise Software Is\u00a0Ending", "href": "https://techcrunch.com/2014/08/05/the-dark-age-of-enterprise-software-is-ending/"}
{"post-title": "Backed By Tencent And Felicis, Scaled Inference Wants To Be The Google Brain For\u00a0Everyone", "href": "https://techcrunch.com/2014/07/29/scaled-inference-2/"}
{"post-title": "Lexalytics Acquires Semantria To Bring Sentiment Analysis To The\u00a0Masses", "href": "https://techcrunch.com/2014/07/14/lexalytics-acquires-semantria-to-bring-sentiment-analysis-to-the-masses/"}
{"post-title": "Salesforce Buys Big Data Startup RelateIQ For Up To\u00a0$390M", "href": "https://techcrunch.com/2014/07/11/salesforce-buys-big-data-startup-relateiq-for-up-to-390m/"}
{"post-title": "Duetto Raises $21M Led By Accel To Equip Hotels With Big Data Surge\u00a0Pricing", "href": "https://techcrunch.com/2014/07/09/duetto/"}
{"post-title": "FuturePerfect Ventures Is A Small Fund Launched To Back Applications For Big\u00a0Data", "href": "https://techcrunch.com/2014/07/04/futureperfect-ventures-is-a-small-fund-launched-to-back-applications-for-big-data/"}
{"post-title": "How A Former Google Data Guy Could Change What We Eat For\u00a0Breakfast", "href": "https://techcrunch.com/2014/07/03/how-a-former-google-data-guy-could-change-what-we-eat-for-breakfast/"}
{"post-title": "Zendesk Insights Shows It\u2019s A Data-Driven\u00a0World", "href": "https://techcrunch.com/2014/06/26/its-a-data-driven-world-and-zendesk-insights-aims-to-surface-detailed-customer-service-analytics/"}
{"post-title": "Couchbase Adds $60 Million As Big Data Demands\u00a0Loom", "href": "https://techcrunch.com/2014/06/26/couchbase-adds-60-million-as-big-data-demands-loom/"}
{"post-title": "CloudPhysics Grabs $15M In Series C Funding And Announces New Virtual Storage Predictive\u00a0Analytics", "href": "https://techcrunch.com/2014/06/23/cloudphysics-grabs-15m-in-series-c-funding-and-announces-new-virtual-storage-predictive-analytics/"}
{"post-title": "RapidMiner Scoops Up Radoop For Hadoop Analytics\u00a0Processing", "href": "https://techcrunch.com/2014/06/16/rapidminer-scoops-up-radoop-for-hadoop-analytics-processing/"}
{"post-title": "Microsoft Announces Azure ML, Cloud-based Machine Learning Platform That Can Predict Future\u00a0Events", "href": "https://techcrunch.com/2014/06/16/microsoft-announces-azure-ml-cloud-based-machine-learning-platform-that-can-predict-future-events/"}
{"post-title": "SiSense Raises $30M More To Bring Big Data Analytics To\u00a0Businesspeople", "href": "https://techcrunch.com/2014/06/12/sisense-raises-30m-more-to-take-big-data-analytics-to-businesspeople/"}
{"post-title": "Combining Big Data And Human Resources Nets Visier $25.5\u00a0Million", "href": "https://techcrunch.com/2014/06/10/combining-big-data-and-human-resources-nets-visier-25-5-million/"}
{"post-title": "DataTorrent, A Big Data Platform Built On Hadoop, Can Process A Billion Events Per\u00a0Second", "href": "https://techcrunch.com/2014/06/03/datatorrent-big-data-processing-platform-built-on-hadoop-can-process-a-billion-events-per-second/"}
{"post-title": "Trifacta Raises $25 Million For Its Data Transformation\u00a0Software", "href": "https://techcrunch.com/2014/05/29/trifacta-raises-25-million-for-its-data-transformation-software/"}
{"post-title": "Actually, Every Company Is a Big Data\u00a0Company", "href": "https://techcrunch.com/2014/05/22/actually-every-company-is-a-big-data-company/"}
{"post-title": "Microsoft, SAP Strengthen Ties With Mobile, Data, Cloud\u00a0Partnership", "href": "https://techcrunch.com/2014/05/19/microsoft-sap-strengthen-ties-with-mobile-data-cloud-partnership/"}
{"post-title": "Celmatix Begins Clinical Trials For Big Data-Based Fertility Planning\u00a0Services", "href": "https://techcrunch.com/2014/05/14/celmatix-begins-clinical-trials-for-big-data-based-fertility-planning-services/"}
{"post-title": "First Class Graduates From Data Elite Big Data\u00a0Lab", "href": "https://techcrunch.com/2014/05/01/first-class-graduates-from-data-elite-big-data-lab/"}
{"post-title": "Aviso Aims To Take Guesswork Out Of Earnings\u00a0Forecasts", "href": "https://techcrunch.com/2014/04/30/aviso-aims-to-take-guess-work-out-of-earnings-forecasts/"}
{"post-title": "Big Data Platform InsideSales.com Raises $100M From Polaris, KPCB At $1B\u00a0Valuation", "href": "https://techcrunch.com/2014/04/28/big-data-platform-insidesales-com-raises-100m-from-polaris-kpcb-at-nearly-1b-valuation/"}
{"post-title": "Datameer Update Brings Instant Visualization To Big Data\u00a0Analytics", "href": "https://techcrunch.com/2014/04/22/datameer-update-brings-instant-visualization-to-big-data-analytics/"}
{"post-title": "Big Data Startup Frrole Raises $245K Angel Round, As Crowdfunding Platforms Seek Growth In\u00a0India", "href": "https://techcrunch.com/2014/04/21/big-data-startup-frrole-raises-245k-angel-round-as-crowdfunding-platforms-seek-growth-in-india/"}
{"post-title": "Harvard-Backed Experfy Wants To Create A McKinsey In The Cloud For Big Data\u00a0Talent", "href": "https://techcrunch.com/2014/03/31/harvard-backed-experfy-wants-to-create-a-mckinsey-in-the-cloud-for-big-data-talent/"}
{"post-title": "Indix Raises Additional $8.5M From Avalon, Nexus To Build World\u2019s Largest Product Database For\u00a0Brands", "href": "https://techcrunch.com/2014/03/26/indix-raises-additional-8-5m-from-avalon-nexus-to-build-worlds-largest-product-database-for-brands/"}
{"post-title": "Google Launches BigQuery Streaming For Real-Time, Big-Data\u00a0Analytics", "href": "https://techcrunch.com/2014/03/25/google-launches-bigquery-streaming-for-real-time-big-data-analytics/"}
{"post-title": "LeanData Raises $5.1M In Series A From Shasta Ventures To Help Customers Make Sense Of Salesforce\u00a0Data", "href": "https://techcrunch.com/2014/03/19/leandata-raises-5-1m-in-series-a-from-shasta-ventures-to-help-customers-make-sense-of-salesforce-data/"}
{"post-title": "New Relic Goes Beyond Server Monitoring And Adds Software\u00a0Analytics", "href": "https://techcrunch.com/2014/03/19/new-relic-goes-beyond-server-monitoring-and-launches-business-analytics-tool/"}
{"post-title": "Reflektion Raises $8M From Intel, Nike To Help Retailers Predict What Shoppers Will Buy\u00a0Next", "href": "https://techcrunch.com/2014/03/04/reflektion-raises-8m-from-intel-nike-to-help-retailers-predict-what-shoppers-will-buy-next/"}
{"post-title": "Target Accelerator\u2019s First Batch In India Bets Big On Social Commerce, Mobile And\u00a0Analytics", "href": "https://techcrunch.com/2014/02/24/target-accelerators-first-batch-in-india-bets-big-on-social-commerce-mobile-and-analytics/"}
{"post-title": "BlueTalon Raises $1.5M In Seed To Offer Single-Click Data Collaboration For\u00a0Enterprises", "href": "https://techcrunch.com/2014/02/21/bluetalon-raises-1-5m-in-seed-to-offer-single-click-data-collaboration-for-enterprises/"}
{"post-title": "42, An Online Platform Bringing Big Data To Brick-And-Mortar Retailers, Makes Its\u00a0Debut", "href": "https://techcrunch.com/2014/02/21/42-an-online-platform-bringing-big-data-to-brick-and-mortar-retailers-makes-its-debut/"}
{"post-title": "With $770K In Seed Funding, Playbasis Wants Businesses In Asia To\u00a0Gamify", "href": "https://techcrunch.com/2014/02/16/with-770k-in-seed-funding-playbasis-wants-businesses-in-asia-to-gamify/"}
{"post-title": "CEB Acquires Indian Talent Analytics Startup Talent Neuron for\u00a0$15M", "href": "https://techcrunch.com/2014/02/11/ceb-in-talks-to-acquire-indian-talent-analytics-startup-talent-neuron/"}
{"post-title": "Microsoft\u2019s Power BI For Office 365 Comes Out Of Preview, Simplifies Data Analysis And\u00a0Visualizations", "href": "https://techcrunch.com/2014/02/10/microsofts-power-bi-for-office-365-comes-out-of-preview-simplifies-data-analysis-and-visualizations/"}
{"post-title": "Thomson Reuters Taps Into Twitter For Big Data Sentiment\u00a0Analysis", "href": "https://techcrunch.com/2014/02/03/twitter-raises-its-enterprise-cred-with-thomson-reuters-sentiment-analysis-deal/"}
{"post-title": "Enigma Raises $4.5M To Help Plumb The Depths And Derive Insights From Public\u00a0Data", "href": "https://techcrunch.com/2014/01/30/enigma-raises-4-5m-from-to-help-plumb-the-depths-of-and-derive-insights-from-public-data/"}
{"post-title": "Still In Stealth, Origami Logic Raises $15M More To Help Marketers Tap The Big Data Mother\u00a0Lode", "href": "https://techcrunch.com/2014/01/29/origami-logic-big-data/"}
{"post-title": "MemSQL Raises $35M Series B Led By Accel\u00a0Partners", "href": "https://techcrunch.com/2014/01/22/memsql-raises-35m-series-b-led-by-accel-partners/"}
{"post-title": "Zephyr Health Lands $15M From Kleiner To Help Life Sciences Navigate Big Data, Bring Therapies To Market\u00a0Faster", "href": "https://techcrunch.com/2014/01/08/zephyr-health-lands-15m-from-kleiner-to-help-life-sciences-navigate-big-data-bring-therapies-to-market-faster/"}
{"post-title": "Impala: Another Google Inspired Platform Enters The Mainstream Data\u00a0World", "href": "https://techcrunch.com/2013/12/15/impala-another-google-inspired-platform-enters-the-mainstream-data-world/"}
{"post-title": "DataSift Launches Vedo To Help Enterprises Channel The Big Social Data\u00a0Firehose", "href": "https://techcrunch.com/2013/12/12/datasift-launches-vedo-to-help-enterprises-to-channel-the-big-social-data-firehose/"}
{"post-title": "Spire Raises $8M In Series A To Help Customers Manage Talent, Prevent Employee\u00a0Fraud", "href": "https://techcrunch.com/2013/12/11/spire-raises-8m-in-series-a-to-help-customers-manage-talent-prevent-employee-fraud/"}
{"post-title": "ClearDATA Lands $14M To Give The Healthcare Industry A HIPAA-Compliant Cloud Alternative To AWS And\u00a0Rackspace", "href": "https://techcrunch.com/2013/12/05/cleardata-lands-14m-to-give-the-healthcare-industry-a-hipaa-compliant-cloud-alternative-to-aws-and-rackspace/"}
{"post-title": "RetailNext Acquires Eric Schmidt-Backed Wi-Fi Analytics Company, Nearbuy\u00a0Systems", "href": "https://techcrunch.com/2013/12/03/retailnext-acquires-eric-schmidt-backed-wi-fi-analytics-company-nearbuy-systems/"}
{"post-title": "Rubikloud Raises $1 Million To Drive Conversion Rates With Big\u00a0Data", "href": "https://techcrunch.com/2013/11/18/rubikloud/"}
{"post-title": "Futurelytics Gets $800K From Index And More So That Small Enterprises Can Access Big Data,\u00a0Too", "href": "https://techcrunch.com/2013/11/11/futurelytics-gets-800k-from-index-and-more-so-that-small-enterprises-can-access-big-data-too/"}
{"post-title": "German Predictive Analytics Startup Rapid-I Rebrands As RapidMiner, Takes $5M From Open Ocean, Earlybird To Tackle The U.S.\u00a0Market", "href": "https://techcrunch.com/2013/11/04/german-predictive-analytics-startup-rapid-i-rebrands-as-rapidminer-takes-5m-from-open-ocean-earlybird-to-tackle-the-u-s-market/"}
{"post-title": "Zuck Knows If You\u2019ve Been Bad Or Good, So Be Good For Goodness\u2019\u00a0Sake", "href": "https://techcrunch.com/2013/10/19/kindly-old-elf-or-cia-spook/"}
{"post-title": "Silk, A Cloud-Based App To Visualize Data, Launches Its First Paid Product For Teams, Gets Another $1.6M From\u00a0NEA", "href": "https://techcrunch.com/2013/10/07/cloud-based-non-techie-data-wrangling-app-silk-launches-its-first-paid-product-for-teams-gets-an-extra-1-6m-from-nea/"}
{"post-title": "Quri, A Retail Intelligence Platform Using Mobile Crowdworkers, Scores $10 Million From Matrix &\u00a0Others", "href": "https://techcrunch.com/2013/10/02/quri-a-retail-intelligence-platform-using-mobile-crowdworkers-scores-10-million-from-matrix-others/"}
{"post-title": "Senior Facebook, Netflix Scientist Joins Identified To Help It Fix Professional Search, Take On\u00a0LinkedIn", "href": "https://techcrunch.com/2013/10/01/senior-facebook-netflix-scientist-joins-identified-to-help-it-fix-professional-search-take-on-linkedin/"}
{"post-title": "Big Data Startup NGDATA Raises $3.3M For Lily, Its Real-Time Customer Offer\u00a0Generator", "href": "https://techcrunch.com/2013/09/24/ngdata-series-a/"}
{"post-title": "64% Of Organizations Have Invested In Or Plan To Invest In Big Data Tech, But Only 8% Have Started Using It, Says\u00a0Gartner", "href": "https://techcrunch.com/2013/09/23/64-of-organizations-have-invested-in-or-plan-to-invest-in-big-data-tech-but-only-8-have-started-using-it-says-gartner/"}
{"post-title": "Google\u2019s BigQuery Introduces Streaming Inserts And Time-Based Queries For Real-Time\u00a0Analytics", "href": "https://techcrunch.com/2013/09/18/googles-bigquery-introduces-streaming-inserts-and-time-based-queries-for-real-time-analytics/"}
{"post-title": "Panorama Education Wants To Make Polling Parents, Students And Teachers Easier For\u00a0Educators", "href": "https://techcrunch.com/2013/08/15/panorama-education-wants-to-make-polling-parents-students-and-teachers-easier-for-educators/"}
{"post-title": "Max Levchin Wants Us To Mine Hurricanes For\u00a0Energy", "href": "https://techcrunch.com/2013/07/31/max-levchin-hurricane-wrestler/"}
{"post-title": "Data Analysis Startup Context Relevant Raises $7M Series A\u00a0Round", "href": "https://techcrunch.com/2013/07/16/context-relevant-raises-7-million-series-a/"}
{"post-title": "Twitter The Ad Player Wants To Push More TV Buttons, Adds Viacom To Its Partner\u00a0List", "href": "https://techcrunch.com/2013/06/19/twitter-the-ad-player-wants-to-push-more-tv-buttons-adds-viacom-to-its-partner-list/"}
{"post-title": "RelateIQ Launches With $29M From Formation 8, Dustin Moskovitz And More To Be Your Next-Gen Relationship\u00a0Manager", "href": "https://techcrunch.com/2013/06/12/relateiq-launches-with-29m-from-formation-8-dustin-moskovitz-and-more-to-be-your-next-gen-relationship-manager/"}
{"post-title": "Zynga Co-founder\u2019s Junyo Is Using Big Data To Help EdTech Companies Better Understand What Schools Really\u00a0Need", "href": "https://techcrunch.com/2013/06/04/zynga-co-founders-junyo-is-using-big-data-to-help-edtech-companies-better-understand-what-schools-really-need/"}
{"post-title": "Big Data Marketers Unite As BloomReach Acqui-hires\u00a0ShopLogic", "href": "https://techcrunch.com/2013/05/30/big-data-marketing/"}
{"post-title": "Photo Albums Are Stupid. Moju Labs Is Building What Comes\u00a0Next.", "href": "https://techcrunch.com/2013/05/22/photo-albums-are-stupid-moju-labs-is-building-what-comes-next/"}
{"post-title": "Enterprise Big Data Platform Cloudera Opens EMEA HQ In East London\u2019s Tech\u00a0City", "href": "https://techcrunch.com/2013/04/22/cloudera-joins-tech-city/"}
{"post-title": "TipSense\u2019s Brilliant Algorithm Reveals Best Dishes At Restaurants, Worst Features In\u00a0Apps", "href": "https://techcrunch.com/2013/04/02/tipsense-dishtip-appcrawlr/"}
{"post-title": "ElectNext Raises $1.3M To Provide Contextual Political Data To News\u00a0Sites", "href": "https://techcrunch.com/2013/04/02/electnext-raises-1-3m-to-provide-contextual-political-data-to-news-sites/"}
{"post-title": "Marketwire Is Now Marketwired, Poaches Yahoo\u2019s Big Data VP As New EVP Of\u00a0Product", "href": "https://techcrunch.com/2013/04/02/marketwire-is-now-marketwired-poaches-yahoos-big-data-vp-as-new-evp-of-product/"}
{"post-title": "Keen On\u2026 So What\u2019s The Big Deal About Big Data?\u00a0[TCTV]", "href": "https://techcrunch.com/2013/03/25/keen-on-so-whats-the-big-deal-about-big-data-tctv/"}
{"post-title": "YC-Backed Fivetran Launches A Smart Online Spreadsheet For Data\u00a0Analysis", "href": "https://techcrunch.com/2013/03/19/yc-backed-fivetran-launches-a-smart-online-spreadsheet-for-data-analysis/"}
{"post-title": "With $2 Million From Andreessen And Others, YC\u2019s Amiato Launches To Bring Big Data A/B Testing With SQL To\u00a0All", "href": "https://techcrunch.com/2013/03/15/backed-with-2m-ycs-amiato-launches-to-bring-big-data-ab-testing-with-sql-to-all/"}
{"post-title": "Looker Takes $2M From First Round And PivotNorth To Build \u2018A Sequel To SQL\u2019 For Business\u00a0Intelligence", "href": "https://techcrunch.com/2013/03/06/looker-takes-2m-from-first-round-and-pivotnorth-to-build-a-sequel-to-sql-for-business-intelligence/"}
{"post-title": "Think Big Raises $3M For \u201cBig Data As A Service\u201d To Give Customers Predictive Powers And New Business\u00a0Insights", "href": "https://techcrunch.com/2013/02/05/think-big-raises-3m-for-big-data-as-a-service-to-give-customers-predictive-powers-and-new-business-insights/"}
{"post-title": "With $100M From The Gates Foundation & Others, inBloom Wants To Transform Education By Unleashing Its\u00a0Data", "href": "https://techcrunch.com/2013/02/05/with-100m-from-the-gates-foundation-others-inbloom-wants-to-transform-education-by-unleashing-its-data/"}
{"post-title": "Big Data And SaaS Will Become Relevant For Small Businesses In\u00a02013", "href": "https://techcrunch.com/2013/01/21/big-data-and-saas-will-finally-become-relevant-for-small-businesses-in-2013/"}
{"post-title": "Founder Stories: Cloudera\u2019s Jeff Hammerbacher On Building Big Data\u00a0Systems", "href": "https://techcrunch.com/2013/01/16/founders-stories-clouderas-jeff-hammerbacher-on-building-big-data-systems/"}
{"post-title": "DARPA-Backed Ayasdi Launches With $10M From Khosla, Floodgate To Uncover The Hidden Value In Big\u00a0Data", "href": "https://techcrunch.com/2013/01/16/darpa-backed-ayasdi-launches-with-10m-from-khosla-floodgate-to-uncover-the-hidden-value-in-big-data/"}
{"post-title": "Infochimps Launches Enterprise Cloud For Big Data\u00a0Analytics", "href": "https://techcrunch.com/2012/12/17/infochimps-launches-enterprise-cloud-for-big-data-analytics/"}
{"post-title": "Big Data Leader Cloudera Raises $65M To Fuel Further Hadoop\u00a0Adoption", "href": "https://techcrunch.com/2012/12/06/big-data-leader-cloudera-raises-65m-to-fuel-further-hadoop-adoption/"}
{"post-title": "Founded By 4 Ex-Googlers, QuBit Raises $7.5M Led By Balderton To Improve E-Commerce Personalization With Big\u00a0Data", "href": "https://techcrunch.com/2012/12/04/founded-by-4-ex-googlers-qubit-raises-7-5m-to-improve-e-commerce-personalization-with-big-data/"}
{"post-title": "Tim Berners-Lee\u2019s Open Data Institute Gets Its First Outside Investment, $750K From The Omidyar Network To Top Up UK\u2019s\u00a0$16M", "href": "https://techcrunch.com/2012/12/02/tim-berners-lees-open-data-institute-gets-its-first-outside-investment-750k-from-the-omidyar-network-to-top-up-uks-16m/"}
{"post-title": "Shrinking Big Data Challenges: Enterprise Storage Startup, Qumulo, Raises $24.5M Series A Led By Highland Capital\u00a0Partners", "href": "https://techcrunch.com/2012/11/20/shrinking-big-data-challenges-enterprise-storage-startup-qumulo-raises-24-5m-series-a-led-by-highland-capital-partners/"}
{"post-title": "Social Analytics Heats Up: Socialbakers Raises $6M From Index And Earlybird To Expand Its Big Brand-Focused Monitoring\u00a0Service", "href": "https://techcrunch.com/2012/11/19/social-analytics-heats-up-socialbakers-raises-6m-from-index-and-earlybird-to-expand-its-big-brand-focused-monitoring-service/"}
{"post-title": "The Most Important Offseason Acquisition For The San Francisco Giants Could Be\u00a0Hadoop", "href": "https://techcrunch.com/2012/11/16/baseball-and-big-data-how-hadoop-and-the-san-francisco-giants-are-taking-on-stats/"}
{"post-title": "Still In Stealth, Origami Logic Gets $9.3M To Help Marketers Unfold And Make Sense Of Big\u00a0Data", "href": "https://techcrunch.com/2012/11/14/still-in-stealth-origami-logic-gets-9-3m-for-a-platform-to-help-marketers-unfold-and-make-sense-of-big-data/"}
{"post-title": "Big Data Visualization Startup Lucky Sort Partners With StockTwits, Lets Investors Chart Stock Trends In\u00a0Real-Time", "href": "https://techcrunch.com/2012/11/01/big-data-visualization-startup-lucky-sort-partners-with-stocktwits-lets-investors-chart-stock-trends-in-real-time/"}
{"post-title": "Data 2.0 Goes Large: InfoArmy Raises $17.3M To Build Out Its Crowdsourced Competitive Intelligence\u00a0Platform", "href": "https://techcrunch.com/2012/10/23/data-2-0-goes-large-infoarmy-raises-17-3m-to-build-out-its-crowdsourced-competitive-intelligence-platform/"}
{"post-title": "Big Data To Drive $232 Billion In IT Spending Through\u00a02016", "href": "https://techcrunch.com/2012/10/17/big-data-to-drive-232-billion-in-it-spending-through-2016/"}
{"post-title": "Telefonica Wants To Turn Its Mobile Data Into A Big Data Business, Launches Dynamic Insights\u00a0Unit", "href": "https://techcrunch.com/2012/10/08/telefonica-wants-to-turn-its-mobile-data-into-a-big-data-business-launches-dynamic-insights-unit/"}
{"post-title": "Alteryx Opens Big Data-Analytics Apps Studio For The Rest Of\u00a0Us", "href": "https://techcrunch.com/2012/10/07/alteryx-opens-big-data-analytics-apps-studio-for-the-rest-of-us/"}
{"post-title": "Big Data Company RainStor Raises $12 Million Series C From Credit Suisse And Rogers Venture\u00a0Partners", "href": "https://techcrunch.com/2012/10/04/big-data-company-rainstor-raises-12-million-series-c-from-credit-suisse-and-rogers-venture-partners/"}
{"post-title": "Accel Partners Big Data Fund Invests $4.3 Million In\u00a0Trifacta", "href": "https://techcrunch.com/2012/10/04/accel-partners-big-data-fund-backs-trifacta-with-4-3-million-investment/"}
{"post-title": "More CIA Money For NoSQL: In-Q-Tel Backs\u00a0Cloudant", "href": "https://techcrunch.com/2012/10/02/more-cia-money-for-nosql-in-q-tel-backs-cloudant/"}
{"post-title": "Quantcast Open Sources Hadoop Distributed File System\u00a0Alternative", "href": "https://techcrunch.com/2012/09/27/quantcast-open-sources-hadoop-distributed-file-system-alternative/"}
{"post-title": "Analytics Company Datameer Raises $6 Million From Redpoint Ventures and Kleiner\u00a0Perkins", "href": "https://techcrunch.com/2012/09/25/analytics-company-datameer-raises-6-million-from-redpoint-ventures-and-kleiner-perkins/"}
{"post-title": "Web Hosting Reviews Are A Cesspool. Review Signal Wants To Fix\u00a0That", "href": "https://techcrunch.com/2012/09/25/web-hosting-reviews-are-a-cesspool-review-signal-wants-to-fix-that/"}
{"post-title": "BlockAvenue Uses Big Data To Assign A Letter Grade To Your\u00a0Neighborhood", "href": "https://techcrunch.com/2012/09/20/blockavenue-launch/"}
{"post-title": "Coders Can\u2019t Put Writers Out Of A Job Yet, But We\u2019d Better Watch Our\u00a0Backs", "href": "https://techcrunch.com/2012/08/25/coders-cant-put-writers-out-of-a-job-yet-but-wed-better-watch-our-backs/"}
{"post-title": "What Happens When Pollsters Are No Better Than\u00a0Psychics?", "href": "https://techcrunch.com/2012/08/25/what-happens-when-pollsters-are-no-better-than-psychics/"}
{"post-title": "Y Combinator Alum BigCalc Makes Hadoop Easier for High Frequency Trading\u00a0Firms", "href": "https://techcrunch.com/2012/08/22/y-combinator-alum-bigcalc-makes-hadoop-easier-for-high-frequency-trading-firms/"}
{"post-title": "Google\u2019s Real Time Big Data Tool Cloned By Apache\u00a0Drill", "href": "https://techcrunch.com/2012/08/17/googles-real-time-big-data-tool-cloned-by-apache-drill/"}
{"post-title": "Founded By Former Expedia Engineers, Stealthy Travel Startup Hopper Closes $12 Million Series\u00a0B", "href": "https://techcrunch.com/2012/08/15/founded-by-former-expedia-engineers-stealthy-travel-startup-hopper-closes-12-million-series-b/"}
{"post-title": "ParStream Raises $5.6 Million For Big Data\u00a0Analysis", "href": "https://techcrunch.com/2012/08/14/parstream-raises-5-6-million-for-big-data-analysis/"}
{"post-title": "Twitter\u2019s Open Source Big Data Tool Comes to the Cloud Courtesy of\u00a0Nodeable", "href": "https://techcrunch.com/2012/07/18/twitter-storm-nodeable-pivot/"}
{"post-title": "Torrid Rate of Growth for Digital Health\u00a0Funding", "href": "https://techcrunch.com/2012/06/25/torrid-rate-of-growth-for-digital-health-funding/"}
{"post-title": "Datahero Wants To Democratize Data Visualization And Analysis, Raises $1M Round Led By Foundry\u00a0Group", "href": "https://techcrunch.com/2012/05/31/datahero-wants-to-democratize-data-visualization-and-analysis-raises-1m-round-led-by-foundry-group/"}
{"post-title": "7 Months In, Here\u2019s The Big Data Download From Massive Health\u2019s \u2018Eatery\u2019 App", "href": "https://techcrunch.com/2012/04/19/massive-health-eatery-app-data-findings/"}
{"post-title": "Vigilent Raises $6.7M From Accel For Intelligent Data Center Energy Management\u00a0System", "href": "https://techcrunch.com/2012/03/26/vigilent-raises-6-7m-from-accel-for-intelligent-data-center-energy-management-system/"}
{"post-title": "More Money For Big Data And The Cloud: OpenView Raises New $200M\u00a0Fund", "href": "https://techcrunch.com/2012/03/21/more-money-for-big-data-and-the-cloud-openview-raises-new-200m-fund/"}
{"post-title": "Medio Debuts Cloud-Based Analytics Platform For Customer Insights On Connected\u00a0Devices", "href": "https://techcrunch.com/2012/03/15/medio-debuts-cloud-based-analytics-platform-for-customer-insights-on-connected-devices/"}
{"post-title": "Lucky Sort Grabs Half A Million For Big Data Visualization On Web &\u00a0iPad", "href": "https://techcrunch.com/2012/02/20/lucky-sort-grabs-half-a-million-for-big-data-visualization-on-web-ipad/"}
{"post-title": "Algorithms/Data vs. Analysts/Reports: Fight!", "href": "https://techcrunch.com/2012/02/04/algorithmsdata-vs-analystsreports-fight/"}
{"post-title": "Big VCs Invest In Big Data Startup\u00a0Continuuity", "href": "https://techcrunch.com/2012/01/25/big-vcs-invest-in-big-data-startup-continuuity/"}
{"post-title": "The Big Data Bottleneck In The Consumer\u00a0Web", "href": "https://techcrunch.com/2011/11/21/the-big-data-bottleneck-in-the-consumer-web/"}
{"post-title": "Big Data Is Less About Size, And More About\u00a0Freedom", "href": "https://techcrunch.com/2010/03/16/big-data-freedom/"}
